language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules

env:
  global:
    - NODE_ENV=test
    - DOCKER_COMPOSE_VERSION=1.25.4

notifications:
  email: false

services:
  - docker

before_install:

install:

before_script:
  - docker volume create --name=mongo_external
  - npm run docker:build
  - echo "Welcome to Naijafotos"
  - npm install
  - sleep 5

script:
  - npm test

after_script:
  - docker-compose down
