version: '3'
volumes:
  mongoData:
    external:
      name: mongo_external
services:
  app:
    container_name: naijafotos
    restart: always
    build: .
    ports:
      - '5000:5000'
    links:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
      - mongoData:/data/db
      - ../../../backups:/backups
    ports:
      - '27017:27017'
